# Generated by Django 3.0.3 on 2020-05-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200504_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='Description',
            field=models.TextField(default='Description'),
        ),
    ]
