# Generated by Django 3.0.3 on 2020-05-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_actualite_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='Categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Categorie'),
        ),
    ]
