# Generated by Django 3.0.3 on 2020-06-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200517_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
