# Generated by Django 3.0.7 on 2020-06-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='Titre',
            field=models.CharField(max_length=200),
        ),
    ]
